# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclass',
            options={'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
    ]
